server:
  port: ${SERVER_PORT:8080}

spring:
  profiles:
    active: ${ACTIVE_PROFILE:local}

aws:
  serviceEndpoint:
    dynamo: ${AWS_ENDPOINT_DYNAMO}
    secretsManager: ${AWS_ENDPOINT_SECRETS_MANAGER}
  signingRegion: ${AWS_SIGNINGREGION}
  accessKey: ${AWS_ACCESSKEY}
  secretKey: ${AWS_SECRETKEY}

spotify:
  authUrl: https://accounts.spotify.com
  apiUrl: https://api.spotify.com/v1
